#yml配置文件 空格不能省
#生产环境配置文件
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 769489912
  jpa:
    hibernate:
#      update:实体类每次发生变化，表结构同样会自动更新
      ddl-auto: none
    show-sql: true

#日志级别
logging:
  level:
    root: warn
    com.liuyewei: info
  file: log/blog-pro.log

server:
  port: 8081
